version: '3.7'
services:
  mongo:
    image: mongo:3
    volumes:
      - ./misc/mongo:/data/db

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    volumes:
      - ./misc/es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
​
  graylog:
    image: graylog/graylog:2.4
    volumes:
      - ./misc/graylog_journal:/usr/share/graylog/data/journal
      - ./misc/graylog/config:/usr/share/graylog/data/config
      - ./misc/graylog/plugin/graylog-plugin-aggregates-2.3.0.jar:/usr/share/graylog/plugin/graylog-plugin-aggregates-2.3.0.jar
    environment:
  # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=rodrigoaraujocavacalcante
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=784f51a21fc1269b818bc6a7a719a87ea1f9d80693f81256a1140288800baa3d
      - GRAYLOG_WEB_ENDPOINT_URI=http://localhost:9500/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9500:9000
      # Sysl  og TCP
      - 515:514
      # Syslog UDP
      - 515:514/udp
      # GELF TCP
      - 12202:12201
      # GELF UDP
      - 12202:12201/udp
​
# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
